ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}-slim

COPY main.py Pipfile* /
COPY Assets/ /Assets
WORKDIR /

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
         libhidapi-libusb0 \
         libusb-1.0-0 \
    && apt-get clean \
    && rm -rf /var/cache/apt /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN python3 -m pip --no-cache-dir install -U 'pipenv==2022.9.24'
RUN pipenv install --system --deploy

CMD python3 /main.py

LABEL "org.opencontainers.image.vendor"="23 Technologies GmbH"
